### ISSUE TITLE
--disable-metrics case

### ISSUE THREAD

**Issue by romantico88** [openstack-exporter/openstack-exporter#199]
Hello, i saw that there is posibillity to disable some metrics.
I want to disable f.ex openstack_nova_server_status, openstack_cinder_status. When i'm using --disable-metric=openstack_server_status, it's not working.

Which names of metrics should i use? those from openstack ceilometer/metrics services or those from exporter? how can i see it?

**Comment by alexeymyltsev** [comment]
Hello, 
As mention in description it should be as service name "-" metric name:
```--disable-metric can be specified in the format: service-metric (i.e: cinder-snapshots)```
It mean you should have 
``` -d nova-server_status -d cinder-volume_status```

**Comment by romantico88** [comment]
i've also try this, exporter is launched, but after making curl to metrics after 11-12 seconds have error:

: panic: runtime error: invalid memory address or nil pointer dereference

``` lip 23 11:26:06 openstack-exporter[8605]: panic: runtime error: invalid memory address or nil pointer dereference
lip 23 11:26:06 openstack-exporter[8605]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x8f11f3]
lip 23 11:26:06 openstack-exporter[8605]: goroutine 28 [running]:
lip 23 11:26:06openstack-exporter[8605]: github.com/openstack-exporter/openstack-exporter/exporters.ListAllServers(0xc000070ba0, 0xc000070720, 0xf1eb40, 0x2)
lip 23 11:26:06openstack-exporter[8605]: /app/exporters/nova.go:289 +0x4f3
lip 23 11:26:06openstack-exporter[8605]: github.com/openstack-exporter/openstack-exporter/exporters.(*BaseOpenStackExporter).RunCollection(0xc000070ba0, 0xc00042bbd0, 0xa60f25, 0x9, 0xc000070720, 0x0, 0x0)
lip 23 11:26:06openstack-exporter[8605]: /app/exporters/exporter.go:98 +0x20c
lip 23 11:26:06openstack-exporter[8605]: github.com/openstack-exporter/openstack-exporter/exporters.(*BaseOpenStackExporter).Collect(0xc000070ba0, 0xc000070720)
lip 23 11:26:06 openstack-exporter[8605]: /app/exporters/exporter.go:121 +0x126
lip 23 11:26:06 openstack-exporter[8605]: github.com/prometheus/client_golang/prometheus.(*Registry).Gather.func1()
lip 23 11:26:06  openstack-exporter[8605]: /go/pkg/mod/github.com/prometheus/client_golang@v1.2.1/prometheus/registry.go:443 +0x19d
lip 23 11:26:06  openstack-exporter[8605]: created by github.com/prometheus/client_golang/prometheus.(*Registry).Gather
lip 23 11:26:06 openstack-exporter[8605]: /go/pkg/mod/github.com/prometheus/client_golang@v1.2.1/prometheus/registry.go:454 +0x57d
```

**Comment by romantico88** [comment]
also i used a default `cinder-snapshots` like i example and metric still presented in exports.

i running exporter like below:

```
/usr/bin/openstack-exporter --os-client-config /etc/openstack-exporter/clouds.yaml --web.listen-address=":9170" mycloud --log.level="debug" -d cinder-snapshots
```

```
time curl http://localhost:9170/metrics 2>&1 | grep snap 
# TYPE openstack_cinder_snapshots gauge
openstack_cinder_snapshots 23
```

**Comment by alexeymyltsev** [comment]
> i've also try this, exporter is launched, but after making curl to metrics after 11-12 seconds have error:
> `(it's happens with disabling nova-server_status)`
> 
> ```
> : panic: runtime error: invalid memory address or nil pointer dereference
> 
> lip 23 11:26:06 openstack-exporter[8605]: panic: runtime error: invalid memory address or nil pointer dereference
> lip 23 11:26:06 openstack-exporter[8605]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x8f11f3]
> lip 23 11:26:06 openstack-exporter[8605]: goroutine 28 [running]:
> lip 23 11:26:06openstack-exporter[8605]: github.com/openstack-exporter/openstack-exporter/exporters.ListAllServers(0xc000070ba0, 0xc000070720, 0xf1eb40, 0x2)
> lip 23 11:26:06openstack-exporter[8605]: /app/exporters/nova.go:289 +0x4f3
> lip 23 11:26:06openstack-exporter[8605]: github.com/openstack-exporter/openstack-exporter/exporters.(*BaseOpenStackExporter).RunCollection(0xc000070ba0, 0xc00042bbd0, 0xa60f25, 0x9, 0xc000070720, 0x0, 0x0)
> lip 23 11:26:06openstack-exporter[8605]: /app/exporters/exporter.go:98 +0x20c
> lip 23 11:26:06openstack-exporter[8605]: github.com/openstack-exporter/openstack-exporter/exporters.(*BaseOpenStackExporter).Collect(0xc000070ba0, 0xc000070720)
> lip 23 11:26:06 openstack-exporter[8605]: /app/exporters/exporter.go:121 +0x126
> lip 23 11:26:06 openstack-exporter[8605]: github.com/prometheus/client_golang/prometheus.(*Registry).Gather.func1()
> lip 23 11:26:06  openstack-exporter[8605]: /go/pkg/mod/github.com/prometheus/client_golang@v1.2.1/prometheus/registry.go:443 +0x19d
> lip 23 11:26:06  openstack-exporter[8605]: created by github.com/prometheus/client_golang/prometheus.(*Registry).Gather
> lip 23 11:26:06 openstack-exporter[8605]: /go/pkg/mod/github.com/prometheus/client_golang@v1.2.1/prometheus/registry.go:454 +0x57d
> ```
> 
> using cinder-volume_status
> 
> its no error, but openstack_cinder_volume_status is still presented on metrics.
> 
> used newest version - downloaded amd64 tar.gz , centos 7 / centos 8.

This panic happened because some of metrics collected in one function. It mean function executed , but if some metic has been desalted then it can not be  written and panic happened. 

We should work on it. We should create new issue about it.

**Comment by alexeymyltsev** [comment]
> also i used a default `cinder-snapshots` like i example and metric still presented in exports.
> 
> i running exporter like below:
> 
> ```
> /usr/bin/openstack-exporter --os-client-config /etc/openstack-exporter/clouds.yaml --web.listen-address=":9170" mycloud --log.level="debug" -d cinder-snapshots
> ```
> 
>  ```
> time curl http://localhost:9170/metrics 2>&1 | grep snap 
> # TYPE openstack_cinder_snapshots gauge
> openstack_cinder_snapshots 23
> ```
> 
> and my question is what i doing wrong?:)

I have tested several times mostly same string 
```go run *.go --os-client-config=./clouds.yaml  --disable-cinder-agent-uuid  default --log.level="debug" -d cinder-snapshots    ``` 
and it works without any problem 
```
time curl http://localhost:9180/metrics 2>&1 | grep snap
curl http://localhost:9180/metrics 2>&1  0,00s user 0,01s system 0% cpu 18,888 total
grep --color=auto --exclude-dir={.bzr,CVS,.git,.hg,.svn} snap  0,01s user 0,00s system 0% cpu 18,888 total
```

**Comment by LaurentDumont** [comment]
I see the same issue with disabling `--disable-metric nova-server_status`. We'd like to remove the data because it's obviously a really expensive metric with bigger clouds.

**Comment by frmorais** [comment]
Is this fixed? I'm having the same issue when using `--disable-slow-metrics`

**Comment by jvleminc** [comment]
@frmorais I closed https://github.com/openstack-exporter/openstack-exporter/issues/208 after upgrading worked.

**Comment by frmorais** [comment]
@jvleminc In my case I'm still getting the 'panic: runtime error' and I'm using latest docker image available.

**Comment by Sharpz7** [comment]
Can you close this, in favor of https://github.com/openstack-exporter/openstack-exporter/issues/200 please? That seems to be the most complete.

**Comment by jvleminc** [comment]
@melendur88 ?
