### ISSUE TITLE
Disable metric without function

### ISSUE THREAD

**Issue by alexeymyltsev** [openstack-exporter/openstack-exporter#200]
i've also try this, exporter is launched, but after making curl to metrics after 11-12 seconds have error:
`(it's happens with disabling nova-server_status)`

``` 
: panic: runtime error: invalid memory address or nil pointer dereference

lip 23 11:26:06 openstack-exporter[8605]: panic: runtime error: invalid memory address or nil pointer dereference
lip 23 11:26:06 openstack-exporter[8605]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x8f11f3]
lip 23 11:26:06 openstack-exporter[8605]: goroutine 28 [running]:
lip 23 11:26:06openstack-exporter[8605]: github.com/openstack-exporter/openstack-exporter/exporters.ListAllServers(0xc000070ba0, 0xc000070720, 0xf1eb40, 0x2)
lip 23 11:26:06openstack-exporter[8605]: /app/exporters/nova.go:289 +0x4f3
lip 23 11:26:06openstack-exporter[8605]: github.com/openstack-exporter/openstack-exporter/exporters.(*BaseOpenStackExporter).RunCollection(0xc000070ba0, 0xc00042bbd0, 0xa60f25, 0x9, 0xc000070720, 0x0, 0x0)
lip 23 11:26:06openstack-exporter[8605]: /app/exporters/exporter.go:98 +0x20c
lip 23 11:26:06openstack-exporter[8605]: github.com/openstack-exporter/openstack-exporter/exporters.(*BaseOpenStackExporter).Collect(0xc000070ba0, 0xc000070720)
lip 23 11:26:06 openstack-exporter[8605]: /app/exporters/exporter.go:121 +0x126
lip 23 11:26:06 openstack-exporter[8605]: github.com/prometheus/client_golang/prometheus.(*Registry).Gather.func1()
lip 23 11:26:06  openstack-exporter[8605]: /go/pkg/mod/github.com/prometheus/client_golang@v1.2.1/prometheus/registry.go:443 +0x19d
lip 23 11:26:06  openstack-exporter[8605]: created by github.com/prometheus/client_golang/prometheus.(*Registry).Gather
lip 23 11:26:06 openstack-exporter[8605]: /go/pkg/mod/github.com/prometheus/client_golang@v1.2.1/prometheus/registry.go:454 +0x57d
```

using cinder-volume_status

its no error, but openstack_cinder_volume_status is still presented on metrics.

used newest version - downloaded amd64 tar.gz , centos 7 / centos 8.

_Originally posted by @romantico88 in https://github.com/openstack-exporter/openstack-exporter/issues/199#issuecomment-885516402_

**Comment by alexeymyltsev** [comment]
This panic happened because some of metrics collected in one function. It mean function executed , but if some metic has been desalted then it can not be written and panic happened.

We should work on it. We should create new issue about it.
