### ISSUE TITLE
Sigterm during image gathering process

### ISSUE THREAD

**Issue by Eli-Tarrago** [openstack-exporter/openstack-exporter#232]
openstack-exporter, version 1.6.0 (branch: master, revision: 59ded6d101bead6e38eaa42dd7d08c5adcac729b)
  build user:       workstation
  build date:       20220517-17:58:11
  go version:       go1.15.2

``` 
May 17 14:05:35 HOSTNAME openstack-exporter.a[16721]: time="2022-05-17T14:05:35-04:00" level=info msg="Collected metrics for exporter: openstack_neutron, metric: network_ip_a
May 17 14:05:35 HOSTNAME openstack-exporter.a[16721]: time="2022-05-17T14:05:35-04:00" level=info msg="Collecting metrics for exporter: openstack_neutron, metric: networks" s
May 17 14:05:35 HOSTNAME openstack-exporter.A[16721]: panic: runtime error: invalid memory address or nil pointer dereference
May 17 14:05:35 HOSTNAME openstack-exporter.A[16721]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x8eb3e1]
May 17 14:05:35 HOSTNAME openstack-exporter.A[16721]: goroutine 106 [running]:
May 17 14:05:35 HOSTNAME openstack-exporter.a[16721]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x8eb3e1]
May 17 14:05:35 HOSTNAME openstack-exporter.a[16721]: goroutine 106 [running]:
May 17 14:05:35 HOSTNAME openstack-exporter.a[16721]: github.com/openstack-exporter/openstack-exporter/exporters.ListImages(0xc0006dff20, 0xc000202720, 0xe25ac0, 0x2)
May 17 14:05:35 HOSTNAME openstack-exporter.a[16721]: /home/a/projects/openstack-exporter/exporters/glance.go:54 +0x461
May 17 14:05:35 HOSTNAME openstack-exporter.a[16721]: github.com/openstack-exporter/openstack-exporter/exporters.(*BaseOpenStackExporter).RunCollection(0xc0006dff20, 0xc00048
May 17 14:05:35 HOSTNAME openstack-exporter.a[16721]: /home/a/projects/openstack-exporter/exporters/exporter.go:99 +0x1ff
May 17 14:05:35 HOSTNAME openstack-exporter.a[16721]: github.com/openstack-exporter/openstack-exporter/exporters.(*BaseOpenStackExporter).Collect(0xc0006dff20, 0xc000202720)
May 17 14:05:35 HOSTNAME openstack-exporter.a[16721]: /home/a/projects/openstack-exporter/exporters/exporter.go:122 +0x128
May 17 14:05:35 HOSTNAME openstack-exporter.a[16721]: github.com/prometheus/client_golang/prometheus.(*Registry).Gather.func1()
May 17 14:05:35 HOSTNAME openstack-exporter.a[16721]: /home/A/go/pkg/mod/github.com/prometheus/client_golang@v1.2.1/prometheus/registry.go:443 +0x1a2
May 17 14:05:35 HOSTNAME openstack-exporter.a[16721]: created by github.com/prometheus/client_golang/prometheus.(*Registry).Gather
May 17 14:05:35 HOSTNAME openstack-exporter.a[16721]: /home/a/go/pkg/mod/github.com/prometheus/client_golang@v1.2.1/prometheus/registry.go:535 +0xe8e
```

**Comment by jspeckman** [comment]
@Eli-Tarrago , thanks for the insight.  I was hoping to avoid compiling though.
