### ISSUE TITLE
panic: runtime error for image gathering

### ISSUE THREAD

**Issue by mstinsky** [openstack-exporter/openstack-exporter#250]
After upgrading the openstack exporter container from version 1.4.0 to 1.6.0 we get a runtime error for the glance image part:

```
time="2022-08-31T08:06:00Z" level=info msg="Collecting metrics for exporter: openstack_glance, metric: images" source="exporter.go:97"
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x85261a]

goroutine 35 [running]:
github.com/openstack-exporter/openstack-exporter/exporters.ListImages(0xc0003180c0, 0x2f?)
	/exporters/glance.go:54 +0x39a
github.com/openstack-exporter/openstack-exporter/exporters.(*BaseOpenStackExporter).RunCollection(0xc0003180c0, 0xc000390d30, {0x97c14e, 0x6}, 0x1?)
	/exporters/exporter.go:99 +0x182
github.com/openstack-exporter/openstack-exporter/exporters.(*BaseOpenStackExporter).Collect(0xc0003180c0, 0xc0000d4f60?)
	/exporters/exporter.go:122 +0x105
github.com/prometheus/client_golang/prometheus.(*Registry).Gather.func1()
	/go/pkg/mod/github.com/prometheus/client_golang@v1.2.1/prometheus/registry.go:443 +0xfb
created by github.com/prometheus/client_golang/prometheus.(*Registry).Gather
	/go/pkg/mod/github.com/prometheus/client_golang@v1.2.1/prometheus/registry.go:454 +0x4c5
```

**Comment by parsa97** [comment]
PR #252 will fix this problem
