### ISSUE TITLE
seg fault with the glance service.

### ISSUE THREAD

**Issue by Eli-Tarrago** [openstack-exporter/openstack-exporter#290]
golang 1.19
Compiled against master.

``` 
Jul 25 09:52:05 server01 openstack-exporter[119330]: panic: runtime error: invalid memory address or nil pointer dereference
Jul 25 09:52:05 server01 openstack-exporter[119330]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x84881a]
Jul 25 09:52:05 server01 openstack-exporter[119330]: goroutine 101 [running]:
Jul 25 09:52:05 server01 openstack-exporter[119330]: github.com/openstack-exporter/openstack-exporter/exporters.ListImages(0xc00011a420, 0x2f?)
Jul 25 09:52:05 server01 openstack-exporter[119330]:         /root/openstack-exporter/exporters/glance.go:54 +0x39a
Jul 25 09:52:05 server01 openstack-exporter[119330]: github.com/openstack-exporter/openstack-exporter/exporters.(*BaseOpenStackExporter).RunCollection(0xc00011a420, 0xc0001e52f0, {0x9a1473, 0x6}, 0x0?)
Jul 25 09:52:05 server01 openstack-exporter[119330]:         /root/openstack-exporter/exporters/exporter.go:99 +0x182
Jul 25 09:52:05 server01 openstack-exporter[119330]: github.com/openstack-exporter/openstack-exporter/exporters.(*BaseOpenStackExporter).Collect(0xc00011a420, 0xc0004b1f60?)
Jul 25 09:52:05 server01 openstack-exporter[119330]:         /root/openstack-exporter/exporters/exporter.go:122 +0x105
Jul 25 09:52:05 server01 openstack-exporter[119330]: github.com/prometheus/client_golang/prometheus.(*Registry).Gather.func1()
Jul 25 09:52:05 server01 openstack-exporter[119330]:         /home/user/projects/pkg/mod/github.com/prometheus/client_golang@v1.2.1/prometheus/registry.go:443 +0x10d
Jul 25 09:52:05 server01 openstack-exporter[119330]: created by github.com/prometheus/client_golang/prometheus.(*Registry).Gather
Jul 25 09:52:05 server01 openstack-exporter[119330]:         /home/user/projects/pkg/mod/github.com/prometheus/client_golang@v1.2.1/prometheus/registry.go:535 +0xb0c
````

**Comment by albertomolina** [comment]
I can confirm this issue with openstack-exporter running on a podman container (1.6.0).

The only workaround found has been disable the image service.

**Comment by Sharpz7** [comment]
Since this has been replicated with a years gap. I am going to assume its still an issue.

**Comment by Sharpz7** [comment]
Hi, I was unable to reproduce this against current main with the information available. Could you please share the Glance API response or exporter logs immediately before the panic, together with the OpenStack and exporter versions? That would help us create a reliable test case.
