### ISSUE TITLE
Running with --disable-metric=nova-server_status crashes the exporter

### ISSUE THREAD

**Issue by dparv** [openstack-exporter/openstack-exporter#302]
The whole executable is:

```
golang-openstack-exporter.openstack-exporter --disable-service.network --disable-slow-metrics --disable-service.load-balancer --disable-service.image --disable-service.volume --disable-service.dns --disable-service.gnocchi --disable-service.orchestration --disable-service.identity --collect-metric-time --disable-metric=nova-server_status --os-client-config=/srv/clouds.yaml default
```

Error logs:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x8b5f47]

goroutine 151 [running]:
github.com/openstack-exporter/openstack-exporter/exporters.ListAllServers(0xc00040f080, 0xc0003b11a0, 0xda70a0, 0x2)
	/home/circleci/project/parts/openstack-exporter/build/exporters/nova.go:297 +0x507
github.com/openstack-exporter/openstack-exporter/exporters.(*BaseOpenStackExporter).RunCollection(0xc00040f080, 0xc0004118d0, 0x9ee5e6, 0x9, 0xc0003b11a0, 0x0, 0x0)
	/home/circleci/project/parts/openstack-exporter/build/exporters/exporter.go:99 +0x1fb
github.com/openstack-exporter/openstack-exporter/exporters.(*BaseOpenStackExporter).Collect(0xc00040f080, 0xc0003b11a0)
	/home/circleci/project/parts/openstack-exporter/build/exporters/exporter.go:122 +0x128
github.com/prometheus/client_golang/prometheus.(*Registry).Gather.func1()
	/home/circleci/project/parts/openstack-exporter/go/pkg/mod/github.com/prometheus/client_golang@v1.2.1/prometheus/registry.go:443 +0x12b
created by github.com/prometheus/client_golang/prometheus.(*Registry).Gather
	/home/circleci/project/parts/openstack-exporter/go/pkg/mod/github.com/prometheus/client_golang@v1.2.1/prometheus/registry.go:454 +0x5ce
```

**Comment by Sharpz7** [comment]
Can you close this, in favor of https://github.com/openstack-exporter/openstack-exporter/issues/200 please? That seems to be the most complete.
